### PR TITLE
Fix build when SIZEOF_INT == SIZEOF_LONG

### LINKED ISSUE #78: posix_spawn_ext.so: undefined symbol: rb_fix2int
I am trying to get Gitlab CE 8.5.8+dfsg-5 working on Ubuntu 16.04 32 bit, using the package in the "universe" repo. That GitLab package installs latest posix_spawn as part of it's install. 0.3.13 causes this error to be raised (in the sidekiq log):

posix_spawn_ext.so: undefined symbol: rb_fix2int

0.3.11 does not appear to have this issue. I have not tried 0.3.12.
ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]
Ubuntu 16.04.2 LTS
Linux 4.4.50-rh54-20170220215556.xenU.i386 #1 SMP Mon Feb 20 22:04:23 UTC 2017 i686 i686 i686 GNU/Linux

### PR DESCRIPTION
**Pull request by pterjan**
Fixes #78

### CODE REVIEW

**Comment by andreasbaumann** [comment]
Blocks building gitlab on Archlinux32. Upvoting this one. :-)

**Comment by NgrNxk** [comment]
Yeah, I haven't been able to build the last 4 releases of gitlab :(. Please fix this one.

**Comment by yrzr** [comment]
I met the same problem #84 . Thought it was about ARM. Now it's clear that it affects all 32bit platforms.

Upvoting this one. 👍

**Comment by limansky** [comment]
Same problem on Gentoo x86

**Comment by tmm1** [comment]
ping @rtomayko

**Comment by rtomayko** [comment]
This generates warnings and fails on my crappy Mac Ruby (2.0.0). Do we care?

```
$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
$ rake build
cd tmp/universal.x86_64-darwin16/posix_spawn_ext/2.0.0
make
compiling ../../../../ext/posix-spawn.c
../../../../ext/posix-spawn.c:64:9: warning: implicit declaration of function 'RB_FIX2INT' is invalid in C99 [-Wimplicit-function-declaration]
                        fd = RB_FIX2INT(obj);
                             ^
1 warning generated.
../../../../ext/posix-spawn.c:64:9: warning: implicit declaration of function 'RB_FIX2INT' is invalid in C99 [-Wimplicit-function-declaration]
                        fd = RB_FIX2INT(obj);
                             ^
1 warning generated.
linking shared-object posix_spawn_ext.bundle
cd -
cp tmp/universal.x86_64-darwin16/posix_spawn_ext/2.0.0/posix_spawn_ext.bundle lib/posix_spawn_ext.bundle
```

```
$ rake test
dyld: lazy symbol binding failed: Symbol not found: _RB_FIX2INT
  Referenced from: /Users/rtomayko/git/posix-spawn/lib/posix_spawn_ext.bundle
  Expected in: flat namespace

dyld: Symbol not found: _RB_FIX2INT
  Referenced from: /Users/rtomayko/git/posix-spawn/lib/posix_spawn_ext.bundle
  Expected in: flat namespace

rake aborted!
SignalException: SIGIOT
/Library/Ruby/Gems/2.0.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)

```

**Comment by rtomayko** [comment]
Works great on Mac 2.4.1:

```
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
$ rake build
mkdir -p tmp/x86_64-darwin16/posix_spawn_ext/2.4.1
cd tmp/x86_64-darwin16/posix_spawn_ext/2.4.1
/opt/rubies/2.4.1/bin/ruby -I. ../../../../ext/extconf.rb
creating Makefile
cd -
cd tmp/x86_64-darwin16/posix_spawn_ext/2.4.1
make
compiling ../../../../ext/posix-spawn.c
linking shared-object posix_spawn_ext.bundle
cd -
cp tmp/x86_64-darwin16/posix_spawn_ext/2.4.1/posix_spawn_ext.bundle lib/posix_spawn_ext.bundle
$ rake test
...
149 runs, 478 assertions, 0 failures, 0 errors, 0 skips
```

I'm :+1: to merge. Anyone worried about standard Mac environments?

**Comment by tmm1** [comment]
It's worth keeping compat. I can take a look tomorrow- should be possible to detect the method via extconf.rb

Can you add me to the repo?

**Comment by rtomayko** [comment]
@tmm1 You have collab. @brianmario and @piki are the other committers. We should open an issue looking for a maintainer. I haven't messed with this for a couple years and I'm not sure GitHub is maintaining?

**Comment by limansky** [comment]
BTW, I've checked this fix on x86 with Ruby 2.3.5. It works.
